# https://circleci.com/docs/docker
machine:
  environment:
    BATS_VER: 0.4.0
  services:
    - docker

dependencies:
  cache_directories:
    - "~/deps"
  pre:
    - if [[ ! -e ~/deps/bats_v${BATS_VER}.tar.gz ]]; then mkdir -p ~/deps; curl -sSL -o ~/deps/bats_v${BATS_VER}.tar.gz https://github.com/sstephenson/bats/archive/v${BATS_VER}.tar.gz; fi
    - tar -xf ~/deps/bats_v${BATS_VER}.tar.gz
    - sudo bats-${BATS_VER}/install.sh /usr/local
  override:
    - docker info
    - docker version
    - ss -tulpn
    - script/build

test:
  override:
    - script/test

# https://circleci.com/docs/configuration#deployment
# https://circleci.com/docs/environment-variables
deployment:
  master:
    branch: master
    owner: jumanjihouse
    commands:
      # Publish official images with both a specific tag and "latest".
      - script/publish.sh latest $(date +%Y%m%dT%H%M)-git-${CIRCLE_SHA1:0:7}
