version: 2
executorType: machine
jobs:
  build:
    working_directory: ~/docker-cloudsploit
    docker:
    environment:
      BATS_VER: 0.4.0
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # - run: docker-compose -f php/docker-compose.yml build
dependencies:
  cache_directories:
    - "~/deps"
  pre:
    - if [[ ! -e ~/deps/bats_v${BATS_VER}.tar.gz ]]; then mkdir -p ~/deps; curl -sSL -o ~/deps/bats_v${BATS_VER}.tar.gz https://github.com/sstephenson/bats/archive/v${BATS_VER}.tar.gz; fi
    - tar -xf ~/deps/bats_v${BATS_VER}.tar.gz
    - sudo bats-${BATS_VER}/install.sh /usr/local
  override:
    - docker info
    - docker version
    - ss -tulpn
    - script/build

test:
  override:
    - script/test

# https://circleci.com/docs/configuration#deployment
# https://circleci.com/docs/environment-variables
#deployment:
#  master:
#    branch: master
#    owner: jumanjihouse
#    commands:
#      # Publish official images with both a specific tag and "latest".
#      - script/publish.sh latest $(date +%Y%m%dT%H%M)-git-${CIRCLE_SHA1:0:7}
