#!/bin/sh
set -e

Echo() {
  echo
  echo '====>' $@
}

Echo Fetch upstream source.
git submodule update --init
git submodule foreach git reset --hard

Echo Patch upstream source.
# patch -p1 /home/circleci/project/src/index.js < /home/circleci/project/src/index.js.patch

Echo Build Docker image.
docker build --rm -t cloudsploit /home/circleci/project/src
docker tag ${IMAGE} gjyoung1974/cloudsploit:latest

Echo Clean upstream source.
git submodule foreach git reset --hard

Echo Image Size
docker images | egrep -i '(size|cloudsploit)'
