#!/bin/sh
set -e

Echo() {
  echo
  echo '====>' $@
}

Echo Fetch upstream source.
# git clone git@github.com:cloudsploit/scans.git ../src/cloudsploit
#git submodule update --init
# git submodule foreach git reset --hard

# Echo Patch upstream source.
# patch -p1 ../src/cloudsploit/index.js < ../src/index.js.patch

Echo Build Docker image.
docker build --rm -t cloudsploit ../src
docker tag 'cloudsploit:latest' 'gjyoung1974/cloudsploit:latest'

Echo Clean upstream source.
git submodule foreach git reset --hard

# Echo Image Size
# docker images | egrep -i '(size|cloudsploit)'
